### PR TITLE
New actions: readdir and put_file

### PR DESCRIPTION
**Pull request by slang-telekom**
Also upgraded node engine and ssh2-sftp-client

### CODE REVIEW

**Comment by jhorbulyk** [comment]
elastic.io GmbH has a policy that contributors to open source elastic.io codebases are required to sign a contributor license agreement (CLA). Unfortunately, we haven't yet finalized the text of this agreement so we can't present for you to sign however we are working to put this in place in the future. This unfortunately means that we can't merge this PR at this time but we can come back to you once this infrastructure is put in place. Again we would like to thank you for your contribution and we hope to more seamlessly incorporate these contributions in the future.

**Comment by jhorbulyk** [comment]
@slang-telekom Are you familiar with [this document about trying to standardize component behaviors across connectors](https://github.com/elasticio/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md) ?  The functionality added in this PR is useful functionality that fills gaps that aren't met by the existing component functionality however the way that you are adding this new functionality doesn't seem to fit into this new model particularly well.

**Comment by jhorbulyk** [comment]
For example:
* [Your `put` action](https://github.com/elasticio/sftp-component/blob/9540ee5faa8a0ae67a1bac005a44278c592a0eda/component.json#L42-L55) could be generalized to a [Create Object By Unique ID](https://github.com/elasticio/sftp-component/blob/9540ee5faa8a0ae67a1bac005a44278c592a0eda/component.json#L42-L55) action (with Filename as the unique ID)
* [Your `readdir` action](https://github.com/elasticio/sftp-component/blob/9540ee5faa8a0ae67a1bac005a44278c592a0eda/component.json#L56-L87) could be generalized to a [Lookup Objects (Plural)](https://github.com/elasticio/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md#lookup-objects-plural) use case where filename is a search criteria.

**Comment by slang-telekom** [comment]
Haven't seen that document yet @jhorbulyk . We'll take it into account. I'll close the Pull Request. We'll be back...

**Pull request closed without merging**
